FROM tomcat:7.0-jre8
RUN mkdir -p /cdb

# RUN
# docker volume create --name WAR_CDB
# docker build -t tomcati .
# docker run --network=network_prod -it -p 8888:8080 --name prod_tomcat -v WAR_CDB:/usr/local/tomcat/webapps tomcati
